#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

env:
  RUSTFLAGS: -D warnings

on:
  push:
    branches: [ main ]
  pull_request:
    # Allow CI to run on all PRs, not just ones targeting main. This allows
    # stacked PRs to be tested.

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
      with:
        toolchain: stable
        default: false
        components: rustfmt
    - name: Check style
      run: cargo fmt -- --check
    - name: Check clippy
      run: cargo clippy --all-targets --all-features

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # 1.81 is the MSRV.
        toolchain: [ stable, "1.81" ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
